<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Property[
    <!ELEMENT Property (land)>

    <!ELEMENT land (land-name, price, tag, rent)>
    <!ELEMENT land-name (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT tag (#PCDATA)>
    <!ELEMENT rent (#PCDATA)>


]>


<Property>

    <land>
        <land-name>204 Mount</land-name>
        <price>₱58,462</price>
        <tag> Olive Road Two</tag>
        <rent>rent | $ 12.000</rent>
    </land>

    <land>
        <land-name> ASUS ROG Crosshair III Dark Hero </land-name>
        <price> ₱28,516</price>
        <tag> ATX AMD Motherboard </tag>
        <rent> AMD AM4 Socket for AMD Ryzen 5000 Series/4000 G-Series/3000 Series/3000 G-Series/2000 Series/2000 G-Series Desktop Processors</rent>
    </land>

    <land>
        <land-name> ASUS ROG Strix B550-F Gaming</land-name>
        <price> ₱12,947.</price>
        <tag> ATX Gaming Motherboard </tag>
        <rent> AMD AM4 Socket and PCIe 4.0: The perfect pairing for 3rd Gen AMD Ryzen CPUs</rent>    
    </land>

     <land>
        <land-name> GIGABYTE X570 AORUS ELITE WIFI</land-name>
        <price> ₱12,644</price>
        <tag> ATX AMD Motherboard </tag>
        <rent>  Supports AMD Ryzen 5000 Series / 5000 G-Series Processors, Supports AMD Ryzen 3rd Gen / 2nd Gen Processors , Supports AMD Ryzen 3rd Gen / 2nd Gen / 1st Gen with Radeon Vega Graphics Processors</rent>
    </land>
    
    <land>
        <land-name> GIGABYTE B550M AORUS PRO-P </land-name>
        <price> ₱8,640 </price>
        <tag> Micro ATX Motherboard </tag>
        <rent>AMD Socket AM4, support for: AMD Ryzen 5000 Series / 3rd Gen Ryzen and 3rd Gen Ryzen with Radeon Graphics Processors</rent>
    </land>

    <land>
        <land-name> MSI MAG B550 TOMAHAWK  </land-name>
        <price>₱11,242</price>
        <tag>ATX AMD Motherboard  </tag>
        <rent> Supports AMD Ryzen 5000 / 4000 G / 3000 Series* processors</rent>
    </land>

       <land>
        <land-name> 2GIGABYTE B550M AORUS PRO-P </land-name>
        <price> ₱8,640 </price>
        <tag> Micro ATX Motherboard </tag>
        <rent>AMD Socket AM4, support for: AMD Ryzen 5000 Series / 3rd Gen Ryzen and 3rd Gen Ryzen with Radeon Graphics Processors</rent>
    </land>

    <land>
        <land-name> 3MSI MAG B550 TOMAHAWK  </land-name>
        <price>₱11,242</price>
        <tag>ATX AMD Motherboard  </tag>
        <rent> Supports AMD Ryzen 5000 / 4000 G / 3000 Series* processors</rent>
    </land>

</Property>

